use_yaw : true

Kx : 1.5
Ky : 0.9
Kz : 1.7
KDz : 0.5
Kyaw : 2.3

velx_limit : 0.5
vely_limit : 0.5
velz_limit : 0.3
yaw_limit : 1.4

desired_subject_ratio : 0.30
subject_ratio_thres : 0.05
lateral_thres : 0.03
ref_x_ratio : 2.0
ref_y_ratio : 0.3
ref_yaw_ratio : 0.25
selfie_height : 1.5
